/*
 * This file is generated by jOOQ.
 */
package ru.psu.org_info_server.model.persistence;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.psu.org_info_server.model.persistence.tables.Employees;
import ru.psu.org_info_server.model.persistence.tables.Organizations;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Info extends SchemaImpl {

    private static final long serialVersionUID = 633022716;

    /**
     * The reference instance of <code>info</code>
     */
    public static final Info INFO = new Info();

    /**
     * The table <code>info.employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>info.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;

    /**
     * No further instances allowed
     */
    private Info() {
        super("info", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Employees.EMPLOYEES,
            Organizations.ORGANIZATIONS);
    }
}
