/*
 * This file is generated by jOOQ.
 */
package ru.psu.org_info_server.model.persistence;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.psu.org_info_server.model.persistence.tables.Employees;
import ru.psu.org_info_server.model.persistence.tables.Organizations;
import ru.psu.org_info_server.model.persistence.tables.records.EmployeesRecord;
import ru.psu.org_info_server.model.persistence.tables.records.OrganizationsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>info</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployeesRecord> EMPLOYEES_PKEY = UniqueKeys0.EMPLOYEES_PKEY;
    public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = UniqueKeys0.ORGANIZATIONS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployeesRecord, OrganizationsRecord> EMPLOYEES__FK_ORGANIZATION_EMPLOYEE = ForeignKeys0.EMPLOYEES__FK_ORGANIZATION_EMPLOYEE;
    public static final ForeignKey<EmployeesRecord, EmployeesRecord> EMPLOYEES__FK_CHIEF_EMPLOYEE = ForeignKeys0.EMPLOYEES__FK_CHIEF_EMPLOYEE;
    public static final ForeignKey<OrganizationsRecord, OrganizationsRecord> ORGANIZATIONS__FK_PARENT_ORGANIZATION = ForeignKeys0.ORGANIZATIONS__FK_PARENT_ORGANIZATION;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<EmployeesRecord> EMPLOYEES_PKEY = Internal.createUniqueKey(Employees.EMPLOYEES, "employees_pkey", new TableField[] { Employees.EMPLOYEES.ID }, true);
        public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = Internal.createUniqueKey(Organizations.ORGANIZATIONS, "organizations_pkey", new TableField[] { Organizations.ORGANIZATIONS.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EmployeesRecord, OrganizationsRecord> EMPLOYEES__FK_ORGANIZATION_EMPLOYEE = Internal.createForeignKey(Keys.ORGANIZATIONS_PKEY, Employees.EMPLOYEES, "fk_organization_employee", new TableField[] { Employees.EMPLOYEES.ORGANIZATION }, true);
        public static final ForeignKey<EmployeesRecord, EmployeesRecord> EMPLOYEES__FK_CHIEF_EMPLOYEE = Internal.createForeignKey(Keys.EMPLOYEES_PKEY, Employees.EMPLOYEES, "fk_chief_employee", new TableField[] { Employees.EMPLOYEES.CHIEF }, true);
        public static final ForeignKey<OrganizationsRecord, OrganizationsRecord> ORGANIZATIONS__FK_PARENT_ORGANIZATION = Internal.createForeignKey(Keys.ORGANIZATIONS_PKEY, Organizations.ORGANIZATIONS, "fk_parent_organization", new TableField[] { Organizations.ORGANIZATIONS.PARENT }, true);
    }
}
