/*
 * This file is generated by jOOQ.
 */
package ru.psu.org_info_server.model.persistence;


import ru.psu.org_info_server.model.persistence.tables.Employees;
import ru.psu.org_info_server.model.persistence.tables.Organizations;


/**
 * Convenience access to all tables in info
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>info.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>info.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;
}
